// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeTrack(arg1:string,arg2:number):Promise<void>;

export function EditExamHighestScore(arg1:number):Promise<number>;

export function EditHighestScores(arg1:any,arg2:boolean):Promise<any>;

export function FileName():Promise<string>;

export function OpenFileDialog():Promise<void>;

export function Scores():Promise<main.ScoresResult>;

export function Track():Promise<string>;

export function Tracks():Promise<Array<string>>;
