// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStudent(arg1, arg2) {
  return window['go']['main']['App']['AddStudent'](arg1, arg2);
}

export function ChangeSem(arg1) {
  return window['go']['main']['App']['ChangeSem'](arg1);
}

export function ChangeTrack(arg1, arg2) {
  return window['go']['main']['App']['ChangeTrack'](arg1, arg2);
}

export function EditExamHighestScore(arg1) {
  return window['go']['main']['App']['EditExamHighestScore'](arg1);
}

export function EditHighestScores(arg1, arg2) {
  return window['go']['main']['App']['EditHighestScores'](arg1, arg2);
}

export function EditStudentExamScore(arg1, arg2) {
  return window['go']['main']['App']['EditStudentExamScore'](arg1, arg2);
}

export function EditStudentScores(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditStudentScores'](arg1, arg2, arg3);
}

export function FileName() {
  return window['go']['main']['App']['FileName']();
}

export function GetStudent(arg1) {
  return window['go']['main']['App']['GetStudent'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Scores() {
  return window['go']['main']['App']['Scores']();
}

export function Track() {
  return window['go']['main']['App']['Track']();
}

export function Tracks() {
  return window['go']['main']['App']['Tracks']();
}
