// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddStudent(arg1:string,arg2:boolean):Promise<void>;

export function ChangeSem(arg1:boolean):Promise<void>;

export function ChangeTrack(arg1:string,arg2:number):Promise<void>;

export function EditExamHighestScore(arg1:number):Promise<void>;

export function EditHighestScores(arg1:any,arg2:boolean):Promise<void>;

export function EditStudentExamScore(arg1:number,arg2:number):Promise<void>;

export function EditStudentScores(arg1:number,arg2:any,arg3:boolean):Promise<void>;

export function FileName():Promise<string>;

export function GetStudent(arg1:number):Promise<void>;

export function OpenFileDialog():Promise<void>;

export function Scores():Promise<main.ScoresResult>;

export function Track():Promise<string>;

export function Tracks():Promise<Array<string>>;
